#! /bin/sh

sxhkd &

bspc monitor -d 00 01 10 11

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a App state=floating
