#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x panel > /dev/null || panel &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier super
bspc config pointer_action1 move

bspc config normal_border_color "#181a1e"
bspc config focused_border_color "#32363c"
