#! /bin/bash

xresource() {
        xrdb -query | grep -E "^(bspwm|\*)\.$1" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d one two three four five

bspc config border_width 1
bpsc config window_gap 16

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config pointer_modifier super
bspc config pointer_action1 move

bspc config normal_border_color ${xresource normalBorderColor}
bspc config focused_border_color ${xresource focusedBorderColor}
