#! /bin/bash

batteryPath="/sys/class/power_supply/BAT1/capacity"

# Source the panel color definitions
. panel_colors

setWindowManagerString() {
        item=$1

        case $item in
                [fou]*)
                        workspaceFg=${colorDefaultFg}
                        workspaceBg=${colorDefaultBg}
                        ;;
                [FOU]*)
                        workspaceFg=${colorFocusedFg}
                        workspaceBg=${colorFocusedBg}
                        ;;
        esac

        wm="${wm}%{F${workspaceFg}}%{B${workspaceBg}} ${item#?} %{B-}%{F-}"
}

while read -r line; do
        case $line in
                SYS*)
                        # System info
                        timeStr=$(date +%H:%M:%S)
                        batteryStr="$(cat ${batteryPath})%"
                        ;;

                W*)
                        wm=""
                        IFS=":"
                        set -- ${line#?}

                        while [ $# -gt 0 ]; do
                                item=$1

                                case $item in
                                        [fFoOuU]*)
                                                setWindowManagerString $item
                                                ;;
                                esac

                                # Get the next item
                                shift
                        done
                        ;;
        esac
        printf "%s\n" "%{l}${wm}%{c}${timeStr}%{r}${batteryStr}"
done
